#define ROW 15
#define COL 15

#define MAX_STAGE 5

#define WALL 1
#define ROAD 0
#define CHEST 2
#define GOAL 3
#define PLAYER -1
#define GOALCHEST 4
#define GOALPLAYER -2
#define VOIDBLOCK 9
#define EIGHTSTAR 8
#define FISH 7
#define OCTOPUS 6
#define SHIP 10
#define WAVE 11
#define CACTUS 12
#define PALM 13
#define BLOSSOM 14


#define BLACK FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN
#define YELLOW FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define LIGHTBLUE FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY

#define UP 72
#define DOWN 80
#define LEFT 75
#define RIGHT 77

#define MAX_UNDO 10000

#define BGM_WAV 101